server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_mall
    username: postgres
    password: auto123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}